# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
      
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8888:8080

volumes:
  db: